// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: ebike_demo

#include "ui.h"

void ui_comp_Dropdown_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Roller_create_hook(lv_obj_t * comp)
{
}
